name: auto commit

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  add_commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: change readme
        run: |
          echo "abc" > ./README.md
          echo "789" > ./LICENSE

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'README.md LICENSE'
          author_name: Gabriele Pongelli
          author_email: gpongelli@users.noreply.github.com

      # changes for other action
      - name: change readme AGAIN
        run: |
          echo "second action" >> ./README.md
          echo "second action" >> ./LICENSE

      # alternative action
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          file_pattern: 'README.md LICENSE'
          commit_user_name: Gabriele Pongelli  # My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: gpongelli@users.noreply.github.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          # commit_author: Gabriele Pongelli <gpongelli@users.noreply.github.com> # defaults to author of the commit that triggered the run
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
