name: auto commit

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  add_commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #- name: change readme
      #  run: |
      #    echo "123" > ./README.md
      #    echo "456" > ./LICENSE

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'README.md LICENSE'
          author_name: Gabriele Pongelli
          author_email: gpongelli@users.noreply.github.com
