name: Matrix OS add variables
on:

  workflow_dispatch:


jobs:
  constraint:
    name: constraint matrix ${{ matrix.os }} - py${{ matrix.python-version }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
        include:
        - os: ubuntu-latest
          tox_os: "lin"
        - os: windows-latest
          tox_os: "win"
        - os: macos-latest
          tox_os: "mac"
        - python-version: "3.11"
          python-sw: "3.11.1"
        - python-version: "3.10"
          python-sw: "3.10.9"
        - python-version: "3.9"
          python-sw: "3.9.16"
        - python-version: "3.8"
          python-sw: "3.8.16"
    runs-on: ${{ matrix.os }}

    outputs:
      os_option: ""

    steps:
      - name: Setup variable
        if: runner.os == 'Windows'
        run: |
          echo "os_option=/d" >> $env:GITHUB_ENV

      - name: print vars
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.python-version }}
          echo ${{ matrix.tox_os }}
          echo ${{ matrix.python-sw }}
          echo ${{ env.os_option }}
