name: Matrix print
on:
  push:
  workflow_dispatch:

env:
  ARM_IMG_TAG: 1.2.1
  PY_311: "3.11"
  PY_311_SW: "3.11.1"
  PY_310: "3.10"
  PY_310_SW: "3.10.5"
  PY_39: "3.9"
  PY_39_SW: "3.9.16"
  PY_38: "3.8"
  PY_38_SW: "3.8.16"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  constraint:
    name: constraint matrix ${{ matrix.arch }} - py${{ matrix.python-sw }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-sw: [ ${{ env.PY_311 }}, ${{ env.PY_310 }}, ${{ env.PY_39 }} ]
        arch: [ armv6l, armv7l, aarch64 ]
        include:
        - arch: armv6l
          python-sw: $PY_311
          cpu: arm1176
          base_image: arm6-py311
          arm_tag: abc-$ARM_TAG-def
        - arch: armv6l
          python-sw: $PY_310
          cpu: arm1176
          base_image: arm6-py310
          arm_tag: abc-$ARM_TAG-def
        - arch: armv6l
          python-sw: $PY_39
          cpu: arm1176
          base_image: arm6-py39
          arm_tag: abc-$ARM_TAG-def

        - arch: armv7l
          python-sw: $PY_311
          cpu: cortex-a7
          base_image: arm7-py311
          arm_tag: abc-$ARM_TAG-def
        - arch: armv7l
          python-sw: $PY_310
          cpu: cortex-a7
          base_image: arm7-py310
          arm_tag: abc-$ARM_TAG-def
        - arch: armv7l
          python-sw: $PY_39
          cpu: cortex-a7
          base_image: arm7-py39
          arm_tag: abc-$ARM_TAG-def

        - arch: aarch64
          python-sw: $PY_311
          cpu: cortex-a53
          base_image: aarch64-py311
          arm_tag: abc-$ARM_TAG-def
        - arch: aarch64
          python-sw: $PY_310
          cpu: cortex-a53
          base_image: aarch64-py310
          arm_tag: abc-$ARM_TAG-def
        - arch: aarch64
          python-sw: $PY_39
          cpu: cortex-a53
          base_image: aarch64-py39
          arm_tag: abc-$ARM_TAG-def

    steps:
      - name: print vars
        run: |
          echo ${{ matrix.arch }}
          echo ${{ matrix.cpu }}
          echo ${{ matrix.python-sw }}
          echo ${{ matrix.base_image }}
          echo $ARM_TAG
          echo ${{ matrix.arm_tag }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-sw }}
