name: Matrix print
on:

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  constraint:
    name: constraint matrix ${{ matrix.arch }} - py${{ matrix.python-sw }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-sw: [ "3.11.1", "3.10.9", "3.9.16" ]
        arch: [ armv6l, armv7l, aarch64 ]
        include:
        - arch: armv6l
          python-sw: "3.11.1"
          cpu: arm1176
          base_image: arm6-py311
        - arch: armv6l
          python-sw: "3.10.9"
          cpu: arm1176
          base_image: arm6-py310
        - arch: armv6l
          python-sw: "3.9.16"
          cpu: arm1176
          base_image: arm6-py39

        - arch: armv7l
          python-sw: "3.11.1"
          cpu: cortex-a7
          base_image: arm7-py311
        - arch: armv7l
          python-sw: "3.10.9"
          cpu: cortex-a7
          base_image: arm7-py310
        - arch: armv7l
          python-sw: "3.9.16"
          cpu: cortex-a7
          base_image: arm7-py39

        - arch: aarch64
          python-sw: "3.11.1"
          cpu: cortex-a53
          base_image: aarch64-py311
        - arch: aarch64
          python-sw: "3.10.9"
          cpu: cortex-a53
          base_image: aarch64-py310
        - arch: aarch64
          python-sw: "3.9.16"
          cpu: cortex-a53
          base_image: aarch64-py39

    steps:
      - name: print vars
        run: |
          echo ${{ matrix.arch }}
          echo ${{ matrix.cpu }}
          echo ${{ matrix.python-sw }}
          echo ${{ matrix.base_image }}
