name: Use built image
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build:
    name: Use built image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-sw: ["3.9.16"]
        arch: [armv6l]
        include:
# arm1176 is the CPU of BCM2835 which is the SOC of first generation RaspberryPi and RaspberryPi Zero.
        - arch: armv6l
          cpu: arm1176
          # base_image: raspios_lite:latest
          base_image: https://github.com/gpongelli/test-action/releases/download/1.0/main-.img.xz
    steps:
      - uses: actions/checkout@v3

      - uses: bhowell2/github-substring-action@v1.0.1
        id: sha_seven
        with:
          value: ${{ github.sha }}
          length_from_start: 7
          output_name: short_sha

      - name: print sha
        run: |
          echo ${GITHUB_SHA}
          echo ${{ steps.sha_seven.outputs.short_sha }}

      - name: Use release image
        uses: pguyot/arm-runner-action@v2
        id: arm_runner_install
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          shell: bash
          copy_repository_path: /opt/repo
          image_additional_mb: 4096
          commands: |
            whoami
            echo $PATH
            echo $LD_LIBRARY_PATH
            ls -l /opt/build_python/installed/bin
            ls -l /opt/build_python/installed/lib
            python3 --version
            /opt/build_python/installed/bin/python3.9 --version
